export enum calculatorValues {
    "Inmuebles habitacionales e instituciones del estado" = 0.12,
    "Inmuebles sin construcción" = 0.06,
    "Inmuebles destinados a Comercio e Industria, y otras actividades" = 0.04,
    "Inmuebles destinados en parte para pequeños negocios y vivienda del propietario del inmueble" = 0.03,
    "Inmuebles destinados para vivienda" = 0.02,
    "Inmuebles destinados a la prestación de servicios públicos del Estado e instituciones autónomas, religiosas y otras no especificadas" = 0.05,
    "Inmuebles baldíos, aunque estuvieran con cercas de alambre, malla ciclón o construcción no especificada" = 0.02,
    "Inmuebles en lotificación, parcelaciones y urbanizaciones en el área urbana" = 0.05,
    "Inmuebles ubicados en los ejes preferenciales y calles principales o donde se brinde el servicio de barrido de calle" = 0.02,
    "En casas de habitación, predios baldíos en proporción al metraje de la construcción" = 0.01,
    "De $0.00 hasta un valor de $2,000.00 de presupuesto, se pagará el 0.5% del total" = 0.5,
    "De $2,000.00 hasta $5,000.00, se pagará el 1% del presupuesto total" = 1,
    "De $5,000.01 hasta $10,000.00, se pagará el 1.5% del presupuesto total" = 1.5,
    "De $10,000.01 en adelante, se pagará el 2% del presupuesto total" = 2,
    "Permiso para situar materiales de construcción en las vías urbanas, sin afectar el transito de vehículos y personas." = 5,
    "Permiso por ampliación o conexión de redes para energía eléctrica conectadas a la red municipal, por persona naturales, ML: 1.00" = 2,
    "Permiso por construcción de gasolinera, se aplicará el 5% sobre el presupuesto de construcción" = 5,
}