import { Houses } from "src/types/house";

const now = new Date();
export const houses2: Houses[] = [
  {
    id: "987ds89ad8f0989fsg",
    state: "Cuscatlan",
    town: "San Bartolome Perulapia",
    latitude: 13.765842,
    longitude: -89.048737,
    property_address_national_registry:
      "Pasaje Las Victorias, Barrio Concepcion",
    property_address_record: "Pasaje Las Victorias, Barrio Concepcion",
    property_picture:
      "https://res.cloudinary.com/du7w5i2uh/image/upload/v1684770403/wallpaperflare.com_wallpaper_jzyfdc.jpg",
    owners_id: "03341956-3",
    property_id_number_national_registry: "5136257",
    cadastral_id_number_from_national_registry: "5136257",
    id_number_municipal_record: 570,
    sequential_number_record: "354",
    volume: "513",
    sheet: "612",
    property_owners_according_deeds_municipal_records: "JUANA LOPEZ CARPIO",
    property_owners_phone_number: "78667045",
    owners_name_national_registry: "JUANA LOPEZ CARPIO",
    name_on_file_municipal_taxes: "JUANA LOPEZ CARPIO",
    municipal_taxes_account_number: "570",
    type_of_property: "Residencial",
    total_area_deeds: 672.48,
    type_of_terrain: "Plano",
    area: "672.48",
    construction_area_owner: 672,
    number_floors_property: 2,
    electricity_meter_number: "95575365",
    sidewalk_condition: "Concreto",
    lineal_meters_property_facing_paved_street_north: 3.5,
    lineal_meters_property_facing_paved_street_south: 0,
    lineal_meters_property_facing_paved_street_east: 0,
    lineal_meters_property_facing_paved_street_west: 0,
    lineal_meters_property_facing_dirt_street_north: 0,
    lineal_meters_property_facing_dirt_street_south: 0,
    lineal_meters_property_facing_dirt_street_east: 0,
    lineal_meters_property_facing_dirt_street_west: 0,
    type_street_property_sits: "Concreto",
    width_street_property_sits_north: 3.1,
    width_street_property_sits_south: 0,
    width_street_property_sits_east: 0,
    width_street_property_sits_west: 0,
    property_value_according_deeds: 1000.0,
    electricity: "",
    running_water: "",
    internet_service: "",
    mobil_data: "",
    road: "",
    comments: "",
    water_source: "",
    sewerage: "",
    electricity_provider: "",
    water_provider: "",
    internet_service_provider: "",
    mobil_data_provider: "",
    public_lights: "",
    trash_collection_service: "",
    street_cleaning_service: "",
    municipal_taxes: 0,
    weather: "",
    altitude: "",
    average_temperature: "",
    average_rainfall: "",
    developing_potential_property: "",
    agricultural_activity: "",
    type_of_agricultural_activity: "",
    type_of_animal_farming: "",
    annual_yielding: "",
    property_risks: "",
    safety_level_area: "",
    proximity_education_centers: "",
    proximity_medical_centers: "",
    distance_main_city: "",
    distance_commercial_port: "",
    distance_airport: "",
    skilled_labor: "",
    unskilled_labor: "",
    type_commercial_activity_property: "",
    commercial_activity_property: "",
    owner_property_owner_business: "",
    business_owner_name: "",
    business_registered_municipal_record: "",
    total_area_property_according_national_registry: 0,
    type_deeds: "",
    property_reference_according_national_registry: "",
    property_owners_email: "",
    parcel_number_national_registry: 0,
    map_number_national_registry: 0,
    mortgage_according_national_registry: "",
    legal_impediment_sale_according_national_registry: "",
    coworker: "",
    working_form_gather_info: "",
    createdAt: now.getTime(),
    updatedAt: now.getTime(),
  },
  {
    id: "789sda08a7698ad987dsa90",
    state: "Cuscatlan",
    town: "San Bartolome Perulapia ",
    latitude: 13.76564,
    longitude: -89.04594,
    property_address_national_registry:
      "Carretera a Suchitoto suburbios, Barrio Concepcion La Curv",
    property_address_record:
      "Carretera a Suchitoto suburbios, Barrio Concepcion La Curv",
    property_picture:
      "https://res.cloudinary.com/du7w5i2uh/image/upload/v1684770408/WhatsApp_Image_2023-05-12_at_8.37.43_AM_x7btuu.jpg",
    owners_id: "02015439-0",
    property_id_number_national_registry: "5633918",
    cadastral_id_number_from_national_registry: "1313",
    id_number_municipal_record: 1313,
    sequential_number_record: "365",
    volume: "515",
    sheet: "617",
    property_owners_according_deeds_municipal_records:
      "CARMEN ELENA DE LA ROSA GUZMAN ",
    property_owners_phone_number: "79246911",
    owners_name_national_registry: "CARMEN ELENA DE LA ROSA GUZMAN ",
    name_on_file_municipal_taxes: "555",
    municipal_taxes_account_number: "555",
    type_of_property: "Residencial",
    total_area_deeds: 79246911,
    type_of_terrain: "Plano",
    area: "254",
    construction_area_owner: 254,
    number_floors_property: 1,
    electricity_meter_number: "98710021",
    sidewalk_condition: "Concreto",
    lineal_meters_property_facing_paved_street_north: 3.2,
    lineal_meters_property_facing_paved_street_south: 0,
    lineal_meters_property_facing_paved_street_east: 0,
    lineal_meters_property_facing_paved_street_west: 0,
    lineal_meters_property_facing_dirt_street_north: 0,
    lineal_meters_property_facing_dirt_street_south: 0,
    lineal_meters_property_facing_dirt_street_east: 0,
    lineal_meters_property_facing_dirt_street_west: 0,
    type_street_property_sits: "Concreto",
    width_street_property_sits_north: 0,
    width_street_property_sits_south: 0,
    width_street_property_sits_east: 0,
    width_street_property_sits_west: 0,
    property_value_according_deeds: 0,
    electricity: "",
    running_water: "",
    internet_service: "",
    mobil_data: "",
    road: "",
    comments: "",
    water_source: "",
    sewerage: "",
    electricity_provider: "",
    water_provider: "",
    internet_service_provider: "",
    mobil_data_provider: "",
    public_lights: "",
    trash_collection_service: "",
    street_cleaning_service: "",
    municipal_taxes: 0,
    weather: "",
    altitude: "",
    average_temperature: "",
    average_rainfall: "",
    developing_potential_property: "",
    agricultural_activity: "",
    type_of_agricultural_activity: "",
    type_of_animal_farming: "",
    annual_yielding: "",
    property_risks: "",
    safety_level_area: "",
    proximity_education_centers: "",
    proximity_medical_centers: "",
    distance_main_city: "",
    distance_commercial_port: "",
    distance_airport: "",
    skilled_labor: "",
    unskilled_labor: "",
    type_commercial_activity_property: "",
    commercial_activity_property: "",
    owner_property_owner_business: "",
    business_owner_name: "",
    business_registered_municipal_record: "",
    total_area_property_according_national_registry: 0,
    type_deeds: "",
    property_reference_according_national_registry: "",
    property_owners_email: "",
    parcel_number_national_registry: 0,
    map_number_national_registry: 0,
    mortgage_according_national_registry: "",
    legal_impediment_sale_according_national_registry: "",
    coworker: "",
    working_form_gather_info: "",
    createdAt: now.getTime(),
    updatedAt: now.getTime(),
  },
];
